{{- if .Values.airflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-airflow
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-webserver
    darwin-component-type: datastore
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: airflow-web
      protocol: TCP
      name: airflow-web
  selector:
    {{- include "darwin.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-webserver
{{- end }}
