{{- if and .Values.airflow.enabled .Values.airflow.rabbitmq.enabled .Values.airflow.rabbitmq.persistence.enabled (not (index .Values.global "local-k8s")) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-airflow-rabbitmq-pvc
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.airflow.rabbitmq.persistence.size }}
{{- end }}
