{{- if .Values.localstack.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-localstack
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
    app.kubernetes.io/component: localstack
    darwin-component-type: datastore
spec:
  type: ClusterIP
  ports:
    - port: 4566
      targetPort: localstack
      protocol: TCP
      name: localstack
  selector:
    {{- include "darwin.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: localstack
{{- end }}
