{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  labels:
    {{- include "feature-store.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.secrets.mysql.password | b64enc | quote }}
{{- end }}
