apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spark-history-server.fullname" . }}
  labels: {{ include "spark-history-server.labels" . | nindent 4 }}
data:
  enablePVC: {{ .Values.pvc.enablePVC | quote }}
  enableGCS: {{ .Values.gcs.enableGCS | quote }}
  enableS3: {{ .Values.s3.enableS3 | quote }}
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- if .Values.pvc.enablePVC }}
  {{- range $key, $val := omit .Values.pvc "enablePVC" }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else if .Values.gcs.enableGCS }}
  {{- range $key, $val := omit .Values.gcs "enableGCS" }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- else if .Values.s3.enableS3 }}
  {{- range $key, $val := omit .Values.s3 "enableS3" }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
