apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-history-server.fullname" . }}
  labels:  {{ include "spark-history-server.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: {{ toYaml .Values.service.annotations | trim | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port.number }}
    targetPort: history-port
    protocol: TCP
    name: {{ .Values.service.port.name }}
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "spark-history-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
