{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-history-server.serviceAccountName" . }}
  labels:  {{ include "spark-history-server.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.serviceAccount.annotations }}
  {{- end }}
{{- end }}
