apiVersion: v1
kind: Service
metadata:
  name: {{ include "remote-kernel.fullname" . }}-kuberay-head-svc
  namespace: {{ .Release.Namespace }}
  labels: {{ include "remote-kernel.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: jupyter
      protocol: TCP
      name: jupyter
  selector:
    {{- include "remote-kernel.selectorLabels" . | nindent 4 }}
