apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: {{.Values.HealthCheckPath}}
    alb.ingress.kubernetes.io/healthcheck-port: "8000"
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/security-groups: {{.Values.SecurityGroup}}
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=120
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    external-dns.alpha.kubernetes.io/hostname: {{.Values.HostName}}	    
  name: {{printf "serve-%s" .Release.Name }}
  namespace: {{.Release.Namespace}}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-kuberay-serve-svc" .Release.Name }}
                port:
                  number: 8000
