apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{.Release.Name }}-prometheus
  namespace: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector:
    matchLabels:
      ray.io/cluster: {{ .Release.Name }}
  podMonitorSelector:
    matchLabels:
      ray.io/cluster: {{ .Release.Name }}
  podMonitorNamespaceSelector: {}
  resources:
    limits:
      cpu: 2
      memory: "4G"
    requests:
      cpu: 1
      memory: "2G"
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name }}-prometheus
  namespace: prometheus
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    prometheus: {{.Release.Name}}-prometheus