{% raw %}
runnerImage:
  image: <your_runner_image>

labels:
  - self-hosted
  - linux
  - X64
  - k8s
  - {% endraw %}{{ cookiecutter.repository_name.lower().strip().replace(' ', '_').replace(':', '_').replace('-', '_') }}{% raw %}

resources:
  limits:
    cpu: 6000m
    memory: 12Gi
  requests:
    cpu: 4000m
    memory: 10Gi


autoscaling:
  enabled: true
  minReplicas: 0
  maxReplicas: 20

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::954754807219:role/ci-cluster-service-account-role"
{% endraw %}