apiVersion: v1
name: spark-history-server
version: 1.0.0
appVersion: 3.3.0
description: A Helm chart for Spark History Server
home: https://spark.apache.org
sources:
  - https://github.com/apache/spark
keywords:
  - spark
  - history-server
