{{- if .Values.modelCache.enabled }}
{{- if not .Values.modelCache.trackingUri }}
{{- fail "modelCache.trackingUri is required when modelCache is enabled" }}
{{- end }}
{{- if not .Values.modelCache.modelUri }}
{{- fail "modelCache.modelUri is required when modelCache is enabled" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "service-deployment.fullname" . }}-mlflow-creds
  labels:
    {{- include "service-deployment.labels" . | nindent 4 }}
    app.kubernetes.io/component: model-cache
type: Opaque
stringData:
  tracking-uri: {{ .Values.modelCache.trackingUri | quote }}
  {{- if .Values.modelCache.trackingUsername }}
  username: {{ .Values.modelCache.trackingUsername | quote }}
  {{- end }}
  {{- if .Values.modelCache.trackingPassword }}
  password: {{ .Values.modelCache.trackingPassword | quote }}
  {{- end }}
{{- end }}

