{{- if .Values.configServer.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "service-deployment.fullname" . }}
  annotations:
    # this is because the name is a deployment time parameter
    # consider also using "cluster-wide" if the namespace is also a parameter
    # please make sure you understand the implications, see README
    sealedsecrets.bitnami.com/cluster-wide: "true"
  labels:
    {{- include "service-deployment.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "service-deployment.labels" . | nindent 8 }}
  encryptedData:
    CONSUL_TOKEN: {{ .Values.configServer.consulToken }}
    VAULT_TOKEN: {{ .Values.configServer.vaultToken }}
{{- end }}