{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "service-deployment.fullname" . }}
  labels:
    {{- include "service-deployment.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: http
      interval: {{ .Values.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "service-deployment.selectorLabels" . | nindent 6 }}
{{- end }}
