{{- if .Values.global.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default "darwin" }}
  labels:
    {{- include "darwin.labels" . | nindent 4 }}
    name: {{ .Values.global.namespace | default "darwin" }}
{{- end }}
