{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-airflow-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "services.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/upstream-vhost: localhost
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: "airflow.localhost"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-airflow
                port:
                  number: 8080
{{- end }}
