{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-airflow-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "services.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /airflow/$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /airflow(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-airflow
                port:
                  number: 8080
{{- end }}
