---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-services
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "services.labels" . | nindent 4 }}
    app.kubernetes.io/component: services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-services
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "services.labels" . | nindent 4 }}
    app.kubernetes.io/component: services
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-services
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "services.labels" . | nindent 4 }}
    app.kubernetes.io/component: services
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-services
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-services
  apiGroup: rbac.authorization.k8s.io
